# Generated by Django 4.2 on 2023-04-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_cart_remove_card_product_id_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
